

security:
  oauth2:
    client:
      client-id: oauth
      client-secret: oauth
      scope: all
      access-token-validity-seconds: 6000
      refresh-token-validity-seconds: 6000
      registered-redirect-uri: http://localhost:7000/getCode
      grant-type: authorization_code,password,refresh_token
      resource-ids: oauth2
    resource:
      id: oauth2
    authorization:
      check-token-access: isAuthenticated()
server:
  port: 7000