

spring:
  datasource:
    url: jdbc:mysql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:3306}/security
    username: ${POSTGRES_USERNAME:root}
    password: ${POSTGRES_PASSWORD:root}
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 3490