
spring:
  datasource:
    url: jdbc:mysql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:3306}/security
    username: ${POSTGRES_USERNAME:root}
    password: ${POSTGRES_PASSWORD:root}
    driver-class-name: com.mysql.jdbc.Driver
  security:
    oauth2:
      storeType: jwt
      jwt:
        SigningKey: oauth2
  redis:
    host: localhost
    port: 6379
server:
  port: 9090